// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in student's study tasks, optionally filtered by completion state.",
  inputSchema: {
    completed: z.boolean().optional().describe("Filter by completion state. Omit for all tasks."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of tasks to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ completed, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tasks").select("id,title,description,priority,deadline,completed,estimated_minutes,subject_id").eq("user_id", ctx.getUserId()).order("deadline", { ascending: true }).limit(limit ?? 25);
    if (typeof completed === "boolean") query = query.eq("completed", completed);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new study task for the signed-in student.",
  inputSchema: {
    title: z2.string().trim().min(1).max(200).describe("Short task title."),
    description: z2.string().trim().max(2e3).optional().describe("Optional task details."),
    priority: z2.enum(["low", "medium", "high"]).default("medium").describe("Task priority."),
    deadline: z2.string().optional().describe("Optional ISO 8601 deadline, e.g. 2026-09-01T18:00:00Z."),
    estimated_minutes: z2.number().int().min(5).max(600).optional().describe("Estimated effort in minutes."),
    subject_id: z2.string().uuid().optional().describe("Optional subject id to attach the task to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      description: input.description ?? null,
      priority: input.priority ?? "medium",
      deadline: input.deadline ?? null,
      estimated_minutes: input.estimated_minutes ?? null,
      subject_id: input.subject_id ?? null,
      completed: false
    }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Complete task",
  description: "Mark one of the signed-in student's tasks as completed.",
  inputSchema: {
    task_id: z3.string().uuid().describe("Id of the task to mark complete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").update({ completed: true, completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", task_id).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Task not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/list-subjects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_subjects_default = defineTool4({
  name: "list_subjects",
  title: "List subjects",
  description: "List the signed-in student's subjects with study hours and completion progress.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum number of subjects to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subjects").select("id,name,color,total_study_hours,completion_percentage,last_studied_at").eq("user_id", ctx.getUserId()).order("name", { ascending: true }).limit(limit ?? 50);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { subjects: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-study-progress.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var get_study_progress_default = defineTool5({
  name: "get_study_progress",
  title: "Get study progress",
  description: "Get the signed-in student's XP, level, streaks and recent study session totals.",
  inputSchema: {
    recent_sessions: z5.number().int().min(1).max(50).default(10).describe("How many recent study sessions to summarize.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ recent_sessions }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profileRes, sessionsRes] = await Promise.all([
      supabase.from("profiles").select("display_name,total_xp,level,current_streak,longest_streak,last_study_date").eq("user_id", userId).maybeSingle(),
      supabase.from("study_sessions").select("id,duration_seconds,focus_score,session_type,start_time,end_time,xp_earned,subject_id").eq("user_id", userId).order("start_time", { ascending: false }).limit(recent_sessions ?? 10)
    ]);
    if (profileRes.error) return { content: [{ type: "text", text: profileRes.error.message }], isError: true };
    if (sessionsRes.error) return { content: [{ type: "text", text: sessionsRes.error.message }], isError: true };
    const sessions = sessionsRes.data ?? [];
    const totalMinutes = Math.round(sessions.reduce((sum, s) => sum + (s.duration_seconds ?? 0), 0) / 60);
    const avgFocus = sessions.length ? Math.round(sessions.reduce((sum, s) => sum + (s.focus_score ?? 0), 0) / sessions.length) : null;
    const summary = {
      profile: profileRes.data ?? null,
      recent_sessions: sessions,
      recent_total_minutes: totalMinutes,
      recent_average_focus_score: avgFocus
    };
    return { content: [{ type: "text", text: JSON.stringify(summary) }], structuredContent: summary };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zvfmlgolzdwqlcufntuo";
var mcp_default = defineMcp({
  name: "study-buddy-hub",
  title: "Study Buddy Hub",
  version: "0.1.0",
  instructions: "Tools for Study Buddy Hub, a study planning and skill-practice app. Use `list_subjects` and `list_tasks` to read the signed-in student's study plan, `create_task` and `complete_task` to manage tasks, and `get_study_progress` for XP, level, streaks and recent study sessions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_subjects_default, list_tasks_default, create_task_default, complete_task_default, get_study_progress_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
